// Mocks generated by Mockito 5.4.5 from annotations
// in my_task_products/test/products_repo_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:my_task_products/core/apis/error/error_model.dart' as _i7;
import 'package:my_task_products/core/network/network_info.dart' as _i8;
import 'package:my_task_products/features/products/data/datasources/local/products_local_data_source.dart'
    as _i3;
import 'package:my_task_products/features/products/data/datasources/remote/products_remote_data_source.dart'
    as _i6;
import 'package:my_task_products/features/products/data/models/product_model.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsLocalDataSource extends _i1.Mock
    implements _i3.ProductsLocalDataSource {
  MockProductsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> cacheUsers(List<_i5.ProductModel>? users) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheUsers,
          [users],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.ProductModel>> getUsersCaching() => (super.noSuchMethod(
        Invocation.method(
          #getUsersCaching,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.ProductModel>>.value(<_i5.ProductModel>[]),
      ) as _i4.Future<List<_i5.ProductModel>>);
}

/// A class which mocks [ProductsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRemoteDataSource extends _i1.Mock
    implements _i6.ProductsRemoteDataSource {
  MockProductsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.ProductModel>> getProducts({
    required dynamic limit,
    required dynamic skip,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
          {
            #limit: limit,
            #skip: skip,
          },
        ),
        returnValue:
            _i4.Future<List<_i5.ProductModel>>.value(<_i5.ProductModel>[]),
      ) as _i4.Future<List<_i5.ProductModel>>);

  @override
  _i4.Future<List<_i5.ProductModel>> filterProducts({
    required String? sortBy,
    required String? order,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterProducts,
          [],
          {
            #sortBy: sortBy,
            #order: order,
          },
        ),
        returnValue:
            _i4.Future<List<_i5.ProductModel>>.value(<_i5.ProductModel>[]),
      ) as _i4.Future<List<_i5.ProductModel>>);

  @override
  _i4.Future<_i2.Either<_i7.ErrorModel, _i5.ProductModel>> addProducts({
    required String? title,
    required String? description,
    required num? discountPercentage,
    required String? shippingInformation,
    required num? price,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProducts,
          [],
          {
            #title: title,
            #description: description,
            #discountPercentage: discountPercentage,
            #shippingInformation: shippingInformation,
            #price: price,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i7.ErrorModel, _i5.ProductModel>>.value(
                _FakeEither_0<_i7.ErrorModel, _i5.ProductModel>(
          this,
          Invocation.method(
            #addProducts,
            [],
            {
              #title: title,
              #description: description,
              #discountPercentage: discountPercentage,
              #shippingInformation: shippingInformation,
              #price: price,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.ErrorModel, _i5.ProductModel>>);

  @override
  _i4.Future<_i2.Either<_i7.ErrorModel, _i5.ProductModel>> updateProduct({
    required String? title,
    required String? description,
    required double? price,
    required int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [],
          {
            #title: title,
            #description: description,
            #price: price,
            #id: id,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i7.ErrorModel, _i5.ProductModel>>.value(
                _FakeEither_0<_i7.ErrorModel, _i5.ProductModel>(
          this,
          Invocation.method(
            #updateProduct,
            [],
            {
              #title: title,
              #description: description,
              #price: price,
              #id: id,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.ErrorModel, _i5.ProductModel>>);

  @override
  _i4.Future<_i2.Either<_i7.ErrorModel, _i5.ProductModel>> deleteProduct(
          {required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [],
          {#id: id},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i7.ErrorModel, _i5.ProductModel>>.value(
                _FakeEither_0<_i7.ErrorModel, _i5.ProductModel>(
          this,
          Invocation.method(
            #deleteProduct,
            [],
            {#id: id},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.ErrorModel, _i5.ProductModel>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i8.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
